name: Release » 'main'

on:
  push:
  release:
    types: [published]

jobs:
  release-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ZIP Component Dir
        run: |
          cd ${{ github.workspace }}/custom_components/kodi_helpers
          zip -r kodi_helpers.zip ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/kodi_helpers/kodi_helpers.zip
          asset_name: kodi_helpers.zip
          tag: ${{ github.ref }}
          overwrite: true